site_name: Despliegue de aplicaciones web
site_url: https://jpradillo.github.io/Docker/
theme:
  name: material
  features:
    - highlight
  
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.highlight:
      linenums: true

nav:
  - 'Tema 6':
    - 'Pr√°ctica 6.1': 'dockerizacion.md'